name: update changelog

on:
    release:
        types: [released]

jobs:
    update:
        permissions:
            contents: write
        uses: laravel/.github/.github/workflows/update-changelog.yml@main
